site_name: F.U.T.U.R.E.S.H.I.T.
site_description: 'Post-Linke Cyberkommune'
site_url: https://futureshit.github.io
  
theme: 
        name: windmill-dark
        locale: de
        favicon: favicon.ico
        include_search_page: true 
        search_index_only: true
nav:
        - Home: index.md
        - Artikel: 
                - Rise up! (2017): articles/riseup.md
                - Nudging (2017): articles/nudging.md
                - An Anarchisten (2018) : articles/call.md
        - Privatsphäre: 
                - Falsche Sicherheit: privacy/falsesec.md
                - Kommerzielle Überwachung: privacy/comsurv.md
                - Properitäre Dienste: privacy/services.md
                - Google? Nein danke!: privacy/android.md
                - Widerstand: privacy/resist.md
        - Medien: 
                - Blogs: media/blogs.md
                - Bücher: media/books.md
                - Dokumentationen: media/docus.md
                - Fiktion: media/fiction.md  
                - Vorträge: media/talks.md     
        - Links:
                - How To: links/howto.md
                - Service Provider: links/provider.md
                - Tools: links/tools.md
                - Sicherheitstests: links/tests.md
                - Operational Security: links/opsec.md
                - Initiativen: links/inis.md
                - Veranstaltungen: links/events.md
                - Karten: links/maps.md
                - Leaks: links/leaks.md
                - OSINT: links/osint.md
                - Sonstiges: links/misc.md


